### ISSUE TITLE
Peer Grading - 9/20

### ISSUE THREAD

**Issue by Chris-Ru** [Chris-Ru/P2-Chickens#25]
Chris: 9.5/10
Shekar: 9.5/10
Sam: 9.5/10
Dylan: 9.5/10

Notes from Crystal:
- Make sure to add notes for the PBL things instead of just corrections
- Link issues because that's where he likes to grade stuff
- Go step by step for the video (format according to rubric) so that he can comprehend things
- Add captions
- Make it abundantly clear whose technical corresponds to who in the video (as well as in ReadMe)

**Comment by jm1021** [comment]
README comment like "Technicals" is not specific enough for me.
