### ISSUE TITLE
Week 5 Grading

### ISSUE THREAD

**Issue by Chris-Ru** [Chris-Ru/P2-Chickens#29]
[RGB Image Minilab](https://poway.instructure.com/courses/107244/assignments/1850689)
[Example](https://github.com/nighthawkcoders/nighthawk_csa/blob/master/src/main/java/com/nighthawk/csa/MainController.java#L29-L63)
[image](https://github.com/nighthawkcoders/nighthawk_csa/blob/master/src/main/resources/templates/starters/image.html)
[grayscale image](https://github.com/nighthawkcoders/nighthawk_csa/blob/master/src/main/resources/templates/starters/image_grayscale.html)
Chris - /10
Shekar - /10
Sam - /10
Dylan - /10

**Comment by avabrooks** [comment]
+0.5 extra credit for complete TPT mini lab
