### ISSUE TITLE
Review Week 7 Group Ticket

### ISSUE THREAD

**Issue by Chris-Ru** [Chris-Ru/P2-Chickens#35]

**Comment by jm1021** [comment]
Tickets are titled by individual.   Sam Working on HTML for grayscale.  Shekar is go back to Fib code, talked a lot about stars system and will work on backend.  Chris wants to input images.   Dylan working on backend.  Concern is if requirements will be covered as reflection is not real clear.   Secondary thinking is limited.

.7.1
